/**
 * Gemini implementation of CoachProvider. Mirrors ClaudeProvider and OpenAiProvider — see the
 * Claude file for why the client is constructed eagerly.
 *
 * Three differences from the other two, all forced by the provider rather than chosen:
 *
 *  - **The persona is a `systemInstruction`, not a message.** Gemini takes system text as its own
 *    field rather than as a turn in the conversation, so the split this interface maintains
 *    between `systemPrompt` and `userContext` has to be joined here. That split exists to place a
 *    prompt-cache breakpoint, and Gemini has no inline marker for one — its caching is an
 *    explicit `CachedContent` object with a substantial minimum token count, which the persona
 *    alone does not reach. So the boundary is preserved in the text (persona first, context
 *    second, separated) but buys nothing yet. Worth revisiting if the persona grows.
 *  - **Roles are `user` and `model`.** Not `assistant`. Mapped on the way in.
 *  - **Schema-constrained output is a first-class request field.** `responseMimeType` plus
 *    `responseSchema` makes the model emit JSON conforming to the schema, so `generatePlan` does
 *    not need the tool-call detour the Claude path uses. The parse is still defended, for the
 *    same reason the OpenAI path defends it: a schema the provider cannot express degrades to
 *    ordinary generation rather than failing loudly.
 *
 *  - **Function calls arrive whole.** Claude streams a tool's JSON as `input_json_delta`
 *    fragments that have to be accumulated per content-block index; Gemini does not. Its
 *    `partialArgs`/`willContinue` fields are documented as unsupported on the Gemini API, so a
 *    `functionCall` part is complete when it appears and `args` is already an object. That
 *    removes the entire class of bug the Claude path's accumulator exists to avoid — there is
 *    no fragment to drop and no index to confuse.
 *  - **Refusal is a finish reason, not a stop reason.** There is no `refusal` verdict; the
 *    candidate comes back with `SAFETY`, `PROHIBITED_CONTENT` and friends, or the prompt itself
 *    is rejected via `promptFeedback.blockReason` with no candidate at all. Both are mapped to
 *    `CoachRefusalError` so the route treats them the same way it treats Claude's.
 */

import {
  aiNutritionMenuSchema,
  aiWorkoutPlanSchema,
  PROPOSE_NUTRITION_MENU_TOOL,
  PROPOSE_WORKOUT_PLAN_TOOL,
} from '@fit/shared/schemas';
import {
  GoogleGenAI,
  type Content,
  type GenerateContentResponse,
  type Tool,
} from '@google/genai';

import { CoachRefusalError } from './provider.js';
import type { CoachContext, CoachMessage, CoachProvider, CoachStreamEvent } from './provider.js';

/**
 * The JSON Schema keywords Gemini documents as supported on `parametersJsonSchema` and
 * `responseJsonSchema`. Anything else is stripped by `toGeminiSchema` below.
 */
const GEMINI_SCHEMA_KEYWORDS = new Set([
  '$id',
  '$defs',
  '$ref',
  '$anchor',
  'type',
  'format',
  'title',
  'description',
  'enum',
  'items',
  'prefixItems',
  'minItems',
  'maxItems',
  'minimum',
  'maximum',
  'anyOf',
  'oneOf',
  'properties',
  'additionalProperties',
  'required',
  'propertyOrdering',
]);

/**
 * Drop schema keywords Gemini does not document support for.
 *
 * The shared tools are generated by `zodToJsonSchema`, and the Zod schemas use `.min()`/`.max()`
 * on strings and `.positive()` on numbers — which emit `minLength`, `maxLength` and
 * `exclusiveMinimum`. None of the three are on Gemini's supported list. Passing them through
 * relies on the API ignoring what it does not recognise, and an API that instead rejects the
 * request would break every proposal with a 400 rather than degrading quietly.
 *
 * Stripping them does NOT weaken the guarantee. The constraints were never enforced by the
 * provider on any path — `parseToolCall` validates the returned args against the same Zod schema
 * regardless, so a plan with an over-long name is rejected here exactly as it would be with
 * Claude. What is lost is only the hint to the model, which the tool description already carries
 * in prose.
 *
 * `properties` and `$defs` are recursed into by VALUE rather than by key: their keys are
 * property and definition names, not keywords, and filtering them would delete the schema.
 */
function toGeminiSchema(node: unknown): unknown {
  if (Array.isArray(node)) return node.map(toGeminiSchema);
  if (node === null || typeof node !== 'object') return node;

  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(node)) {
    if (!GEMINI_SCHEMA_KEYWORDS.has(key)) continue;

    if (key === 'properties' || key === '$defs') {
      const inner: Record<string, unknown> = {};
      for (const [name, sub] of Object.entries(value as Record<string, unknown>)) {
        inner[name] = toGeminiSchema(sub);
      }
      out[key] = inner;
    } else if (key === 'enum' || key === 'required' || key === 'propertyOrdering') {
      // Arrays of plain values, not of schemas. Recursing would be harmless but says the wrong
      // thing about what they contain.
      out[key] = value;
    } else {
      out[key] = toGeminiSchema(value);
    }
  }
  return out;
}

/**
 * The same two tools the Claude path declares, in Gemini's shape.
 *
 * `parametersJsonSchema` rather than `parameters`: the shared package hands over a plain JSON
 * Schema and `parameters` wants the SDK's narrower `Schema` type. Passing the raw schema to the
 * field built to accept one avoids a cast that would claim a compatibility nobody has checked.
 */
const TOOLS: Tool[] = [
  {
    functionDeclarations: [
      {
        name: PROPOSE_WORKOUT_PLAN_TOOL.name,
        description: PROPOSE_WORKOUT_PLAN_TOOL.description,
        parametersJsonSchema: toGeminiSchema(PROPOSE_WORKOUT_PLAN_TOOL.input_schema),
      },
      {
        name: PROPOSE_NUTRITION_MENU_TOOL.name,
        description: PROPOSE_NUTRITION_MENU_TOOL.description,
        parametersJsonSchema: toGeminiSchema(PROPOSE_NUTRITION_MENU_TOOL.input_schema),
      },
    ],
  },
];

/**
 * Finish reasons that mean the model declined, as opposed to failed.
 *
 * Kept as an explicit set rather than "anything that is not STOP": `MAX_TOKENS` is a truncation
 * and `MALFORMED_FUNCTION_CALL` is a fault on our side of the schema — neither is a refusal, and
 * reporting them as one would tell the user the coach would not answer when in fact it tried.
 */
const REFUSAL_FINISH_REASONS = new Set([
  'SAFETY',
  'RECITATION',
  'BLOCKLIST',
  'PROHIBITED_CONTENT',
  'SPII',
  'IMAGE_SAFETY',
  'IMAGE_PROHIBITED_CONTENT',
]);

export { toGeminiSchema as __toGeminiSchemaForTests };

export interface GeminiProviderOptions {
  apiKey: string;
  model: string;
}

export class GeminiProvider implements CoachProvider {
  readonly name = 'gemini' as const;
  private readonly client: GoogleGenAI;
  readonly model: string;

  constructor(options: GeminiProviderOptions) {
    this.client = new GoogleGenAI({ apiKey: options.apiKey });
    this.model = options.model;
  }

  /**
   * Persona then athlete, blank line between.
   *
   * Kept in that order even though nothing currently caches on it: the order is what a future
   * `CachedContent` would need, and reversing it now would mean the stable text no longer sits
   * at the front when that becomes worth doing.
   */
  private systemInstruction(ctx: CoachContext): string {
    return `${ctx.systemPrompt}\n\n${ctx.userContext}`;
  }

  /** `assistant` is this codebase's word for it; Gemini's is `model`. */
  private toContents(messages: CoachMessage[]): Content[] {
    return messages.map((m) => ({
      role: m.role === 'assistant' ? 'model' : 'user',
      parts: [{ text: m.content }],
    }));
  }

  /**
   * Ask for a stream, and settle for a single response if streaming is not on offer.
   *
   * Not every key can reach `:streamGenerateContent`. On the account this was first run
   * against, `ListModels` advertised `generateContent` for every model and the streaming
   * method for none of them — and calling a method a resource does not expose returns 404,
   * exactly as a missing model does. That ambiguity cost an afternoon: the model name was
   * correct the whole time and the error pointed at the model.
   *
   * Rather than decide which account gets which, both are handled. The fallback yields the
   * whole answer as one chunk, so the coach replies in a single block instead of typing itself
   * out — a visibly worse experience, and a far better one than an error.
   *
   * Only 404 falls back. A refusal, a rate limit or a bad key must surface as themselves.
   */
  private async requestStream(
    ctx: CoachContext,
    messages: CoachMessage[],
  ): Promise<AsyncIterable<GenerateContentResponse>> {
    const request = {
      model: this.model,
      contents: this.toContents(messages),
      config: {
        systemInstruction: this.systemInstruction(ctx),
        maxOutputTokens: 4096,
        tools: TOOLS,
      },
    };

    try {
      return await this.client.models.generateContentStream(request);
    } catch (error) {
      const status = (error as { status?: unknown }).status;
      if (status !== 404) throw error;

      const response = await this.client.models.generateContent(request);
      // Wrapped in an async iterable of one, so the loop below stays the only place that reads
      // chunks and neither path needs its own copy of the tool-call and refusal handling.
      return (async function* single() {
        yield response;
      })();
    }
  }

  async *streamChat(ctx: CoachContext, messages: CoachMessage[]): AsyncIterable<CoachStreamEvent> {
    const stream = await this.requestStream(ctx, messages);

    // Whichever verdict the last chunk carried. Read after the loop rather than thrown from
    // inside it, matching the Claude path: a refusal can land after some prose has already gone
    // out, and the caller needs to learn the answer was truncated rather than never started.
    let finishReason: string | undefined;
    let blockReason: string | undefined;

    for await (const chunk of stream) {
      const text = chunk.text;
      // A chunk can carry no text at all — a safety verdict, or the final one with only usage
      // metadata. Yielding an empty event would put a no-op through the SSE stream and, on the
      // client, look briefly like the coach said nothing.
      if (text) yield { type: 'text', text };

      for (const call of chunk.functionCalls ?? []) {
        // `name` and `args` are both optional on the SDK's type. A call with neither is not
        // something to parse — skipping beats throwing on a shape the model is not supposed to
        // be able to produce.
        if (!call.name) continue;
        yield this.parseToolCall(call.name, call.args ?? {});
      }

      const candidateFinish = chunk.candidates?.[0]?.finishReason;
      if (candidateFinish) finishReason = candidateFinish;
      const promptBlock = chunk.promptFeedback?.blockReason;
      if (promptBlock) blockReason = promptBlock;
    }

    // A blocked prompt never produces a candidate, so it is reported on its own field and has to
    // be checked separately rather than folded into the finish reason.
    if (blockReason) throw new CoachRefusalError(blockReason);
    if (finishReason && REFUSAL_FINISH_REASONS.has(finishReason)) {
      throw new CoachRefusalError(finishReason);
    }
  }

  /**
   * Validate a function call against the same Zod schema its declaration was generated from.
   *
   * Unlike the Claude path there is no JSON to parse — `args` arrives as an object — but it is
   * still validated rather than trusted. A schema shown to a model is not a schema it always
   * obeys, and an unvalidated plan reaching the UI would be a card the user could apply to their
   * training with fields the app never checked.
   */
  private parseToolCall(toolName: string, args: Record<string, unknown>): CoachStreamEvent {
    if (toolName === PROPOSE_WORKOUT_PLAN_TOOL.name) {
      return { type: 'plan_proposal', plan: aiWorkoutPlanSchema.parse(args) };
    }
    if (toolName === PROPOSE_NUTRITION_MENU_TOOL.name) {
      return { type: 'nutrition_proposal', menu: aiNutritionMenuSchema.parse(args) };
    }
    throw new Error(`Unknown tool call from model: ${toolName}`);
  }

  async generatePlan<T>(
    ctx: CoachContext,
    jsonSchema: Record<string, unknown>,
    prompt: string,
  ): Promise<T> {
    const response = await this.client.models.generateContent({
      model: this.model,
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      config: {
        systemInstruction: this.systemInstruction(ctx),
        responseMimeType: 'application/json',
        // `responseJsonSchema`, not `responseSchema`. The caller hands over a plain JSON Schema
        // (derived from the Zod schemas in packages/shared) and `responseSchema` wants the SDK's
        // narrower `Schema` type. The SDK does migrate a raw schema across for backward
        // compatibility, but naming the right field says what is being passed instead of relying
        // on it being rescued.
        responseJsonSchema: toGeminiSchema(jsonSchema),
        maxOutputTokens: 8192,
      },
    });

    const text = response.text;
    if (!text) {
      throw new Error('gemini provider: the model returned no content for generatePlan()');
    }

    try {
      return JSON.parse(text) as T;
    } catch {
      // Defended rather than trusted. `responseSchema` is enforced for schemas Gemini can
      // express; one it cannot degrades to ordinary generation, and the failure then arrives as
      // prose where JSON was expected. A parse error naming the provider is far easier to act on
      // than a Zod error deep in the route.
      throw new Error('gemini provider: generatePlan() returned content that was not valid JSON');
    }
  }
}
